# Generated by Django 4.0.4 on 2022-07-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_senser2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senser2',
            old_name='x',
            new_name='value',
        ),
    ]
