# Generated by Django 4.0.4 on 2022-08-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.CharField(max_length=400)),
                ('DeviceName', models.CharField(max_length=400)),
                ('SensorName', models.CharField(max_length=400)),
                ('x', models.FloatField(max_length=400)),
                ('y', models.FloatField(max_length=400)),
                ('z', models.FloatField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
