# Generated by Django 4.0.4 on 2022-09-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='x',
            new_name='X',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='y',
            new_name='Y',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='z',
            new_name='Z',
        ),
    ]
